### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by manofsteele** [manofsteele/perestrava#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can't use certain features without logging in
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by eshoule** [comment]
Good job! Address the uncheck items below, and I will close the issue.

# User Auth

## Functionality

- [ ] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [ ] The site should look exactly like the actual site
* Is there supposed to be a photo on the splash page?
* Could improve fonts/styling some to look more like actual site

- [x] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)

**Comment by manofsteele** [comment]
Thanks for taking a look. A few questions: 

—Fixed the link for main button 
—What exactly is going on with the post-login redirect? I can’t load those pages when I do it — I see that the url in the browser doesn’t change; is this what needs to happen? How is that done?
—Need to research some of the other things, like what to do when pressing enter rather than submit; resetting errors; not moving elements when errors render; random route redirect
—looking like exact site — I kind of combined the splash, login, and signup pages, which are three separate pages on the real Strava, one of which involves a pop-up modal, and another of which involves a redirect from the front page to a separate sign-up page. Other clones I looked at did similar things, sometimes skipping the splash entirely. They also used some of their own styling and fonts. I can re-do all this if necessary, probably by sometime this weekend.

**Comment by eshoule** [comment]
Yes, when you are logged in, you should not be able to go to /login even if it doesn't render the login page. You should be able to do it with you <Switch> statement and your Protect/Auth Routes that are created in the route_util.jsx file. You should be able to take care of your random route redirect with this as well.

Ignore the 'pressing enter' uncheck box - yours is working appropriately. I will check it.

You don't need to redo it! It just looks a little odd going to a completely blank page with only a header - if anything just add a photo or something.

**Comment by eshoule** [comment]
Yay!
